version: '3.7'
services:
  backend:
    container_name: backend
    image: web-app-template-backend:latest
    build:
      context: ./backend
    ports:
      - '${DEVELOPMENT_BACKEND_PORT}:${DEVELOPMENT_BACKEND_PORT}'
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    networks:
      - web-app-network
  frontend:
    image: web-app-template-frontend:latest
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - '${DEVELOPMENT_FRONTEND_PORT}:${DEVELOPMENT_FRONTEND_PORT}'
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - web-app-network
networks:
  web-app-network:
